#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

services:
  dspacedb:
    image: 4science/dspace-cris-postgres-loadsql:${DSPACE_VER:-dspace-cris-2025_02_x}
    environment:
      # This SQL is available from https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data
      LOADSQL: https://github.com/4Science/DSpace-CRIS-Files/releases/download/cris-2024.02.00/db-entities.sql